# this workflow may be run if there are leftover files in the runner workspace 
name: Clean up workspace

on: [workflow_dispatch]

jobs:
  cleanup:
    name: Cleanup
    runs-on: self-hosted
    steps:
      - name: Cleanup
        uses: AutoModality/action-clean@v1
          
          
