name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build Maroon
    runs-on: windows-latest
    steps:
      # pull repo
      - name: Checkout
        uses: actions/checkout@v3
      
      # Caching
      #- uses: actions/cache@v3
      #  with:
      #    path: Library
      #    key: Library-${{ hashFiles('./unity/Assets/**', './unity/Packages/**', './unity/ProjectSettings/**') }}
      #    restore-keys: |
      #      Library-

      # build
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          customImage: 'unityci/editor:windows-2020.3.28f1-universal-windows-platform-1.0.1'
          targetPlatform: StandaloneWindows
          projectPath: ./unity/
      
      # artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
