name: Build

on: push

jobs:
  build:
    name: Build Maroon
    runs-on: ubuntu-latest
    steps:
      # pull repo
      - name: Checkout
        uses: actions/checkout@v3
      
      # Caching
      #- uses: actions/cache@v3
      #  with:
      #    path: Library
      #    key: Library-${{ hashFiles('./unity/Assets/**', './unity/Packages/**', './unity/ProjectSettings/**') }}
      #    restore-keys: |
      #      Library-

      # build
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          #targetPlatform: StandaloneWindows
          buildMethod: Maroon.Build.BuildPlayer.BatchModeBuild
          customParameters: -type LAB -platform PC -output /build
          projectPath: ./unity/
      
      # artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
