name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build Maroon
    runs-on: ubuntu-latest
    steps:
      # pull repo
      - name: Checkout
        uses: actions/checkout@v2
      
      # Caching
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('./unity/Assets/**', './unity/Packages/**', './unity/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # build
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows
          projectPath: ./unity/
      
      # artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
