name: Build

on: push

jobs:
  build:
    name: Build Maroon
    runs-on: ubuntu-latest
    steps:
      # pull repo
      - name: Checkout
        uses: actions/checkout@v3
      
      # Caching
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/unity/Library
          key: Library-${{ hashFiles('${{ github.workspace }}/unity/unity/Assets/**', '${{ github.workspace }}/unity/unity/Packages/**', '${{ github.workspace }}/unity/unity/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # build
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          #targetPlatform: StandaloneWindows
          buildMethod: Maroon.Build.BuildPlayer.BatchModeBuild
          customParameters: -maroonBuildType LAB -maroonBuildTarget PC -maroonBuildPath build
          projectPath: ./unity
          buildsPath: build
      
      # artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
          #path: ${{ github.workspace }}/build
          
