name: steam-testing

on: 
  workflow_dispatch
  
jobs:
  test:
    name: test
    runs-on: self-hosted
    steps:
      - name: dummy
        run: |
          mkdir dummy
          date > dummy/dummy.txt
          
      
      - name: deploy
        uses: mfbrantner/steam-deploy@v0.3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          appId: ${{ secrets.STEAM_APP_ID }}
          buildDescription: testing steam deploy
          rootPath: dummy
          depot2Path: .
          releaseBranch: development
   

  cleanup:
    name: Cleanup
    runs-on: self-hosted
    needs: [test]
    if: ${{ always() }}
    steps:
      - name: Cleanup
        uses: AutoModality/action-clean@v1
          
          
