name: steam-testing

on: 
  workflow_dispatch
  
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: |
          mkdir dummy
          date > dummy/dummy.txt
          
      
      - name: deploy
        uses: game-ci/steam-deploy@v2
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
          ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
          appId: ${{ secrets.STEAM_APP_ID }}
          buildDescription: testing steam deploy
          rootPath: dummy
          depot2Path: .
          releaseBranch: development
   

  # cleanup:
  #   name: Cleanup
  #   runs-on: self-hosted
  #   needs: [test]
  #   if: ${{ always() }}
  #   steps:
  #     - name: Cleanup
  #       uses: AutoModality/action-clean@v1
          
          
